### ISSUE TITLE
ComBinlogDump overflow issue

### ISSUE THREAD

**Issue by altmannmarcelo** [blackbeam/rust_mysql_common#100]
The `struct ComBinlogDump` defines `pos` field as 32bits which I think is due to https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_size ensure we will rotate the binlog after the max value 1073741824 (1G). 
However, that is not a hard limit.

> A transaction is written in one chunk to the binary log, so it is never split between several binary logs. Therefore, if you have big transactions, you might see binary log files larger than [max_binlog_size](https://dev.mysql.com/doc/refman/8.0/en/replication-options-binary-log.html#sysvar_max_binlog_size).

How to reproduce:

```
START TRANSACTION;
# 4GB worth of DML
COMMIT;
```

The `pos` field will overflow.

**Comment by blackbeam** [comment]
Hi.
No, this is due to: https://github.com/mysql/mysql-server/blob/trunk/sql/rpl_source.cc#L961

Please consider using https://docs.rs/mysql/latest/mysql/struct.BinlogRequest.html#method.with_use_gtid
