### ISSUE TITLE
TinyInt not parsed correctly to bool (in accordance to the mysql/mariadb spec)

### ISSUE THREAD

**Issue by thed0ct0r** [blackbeam/rust_mysql_common#133]
I had recommended the use of mysql_async to someone who wanted to try and convert an old legacy application to rust code.
some of their older tables have values other than 1 with the meaning of "true" in boolean - in accordance with the mysql specification (from v5.0.3 onwards).
[https://dev.mysql.com/doc/refman/5.7/en/numeric-type-syntax.html](url) more specifically:

![tinyint-boolean-Screenshot_1](https://github.com/blackbeam/rust_mysql_common/assets/2512952/97f5635d-f413-4ad2-98fd-a40a98e99d8a)

which basically means that any value in the range -128..=127 (excluding 0) should translate to "true".
i have checked the jdbc driver for mysql and it indeed does something similar (value -1 to maxint excluding 0).
with a bunch of other drivers also supporting the uint case as well (some support the chars 'y' and 'n' as well - that i could not find in the spec).

would you be willing to consider supporting the mysql/mariadb spec "as is"?
this would only require changing a single line in: src/value/convert/mod.rs
from:
```
impl TryFrom<Value> for ParseIrOpt<bool> {
    type Error = FromValueError;

    fn try_from(v: Value) -> Result<Self, Self::Error> {
        match v {
            Value::Int(0) => Ok(ParseIrOpt::Ready(false)),
            Value::Int(1) => Ok(ParseIrOpt::Ready(true)),
            Value::Bytes(ref bytes) => match bytes.as_slice() {
                [b'0'] => Ok(ParseIrOpt::Parsed(false, v)),
                [b'1'] => Ok(ParseIrOpt::Parsed(true, v)),
                _ => Err(FromValueError(v)),
            },
            v => Err(FromValueError(v)),
        }
    }
}
```

to:
```
impl TryFrom<Value> for ParseIrOpt<bool> {
    type Error = FromValueError;

    fn try_from(v: Value) -> Result<Self, Self::Error> {
        match v {
            Value::Int(0) => Ok(ParseIrOpt::Ready(false)),
            Value::Int(-128..=127) => Ok(ParseIrOpt::Ready(true)),
            Value::Bytes(ref bytes) => match bytes.as_slice() {
                [b'0'] => Ok(ParseIrOpt::Parsed(false, v)),
                [b'1'] => Ok(ParseIrOpt::Parsed(true, v)),
                _ => Err(FromValueError(v)),
            },
            v => Err(FromValueError(v)),
        }
    }
}
```

with no downsides as far as i can see - only some better compatibility with legacy apps.
if you decide this is something you are willing to do - i would be happy to send this as a pull request (though this is just a change to a single line) and add some tests (as i did not see any - perhaps i missed them?).

**Comment by blackbeam** [comment]
Hi.

> if you decide this is something you are willing to do - i would be happy to send this as a pull request (though this is just a change to a single line) and add some tests (as i did not see any - perhaps i missed them?).

I'm open to this change but I think we should treat every non-zero integer as `true` to act more like an official connector (this is to be compatible with other environments, e.g. Java).

**Comment by thed0ct0r** [comment]
great, appreciate your openness to this.
just to be sure before i make the pull request - am i understanding you correctly with the below chang?

you mean that instead of this:
```
Value::Int(0) => Ok(ParseIrOpt::Ready(false)),
Value::Int(-128..=127) => Ok(ParseIrOpt::Ready(true)),
```

we should use this: (?)
```
Value::Int(0) => Ok(ParseIrOpt::Ready(false)),
Value::Int(_) => Ok(ParseIrOpt::Ready(true)),
```
