### ISSUE TITLE
Confusion about JSON type in binlog parsing

### ISSUE THREAD

**Issue by artorias1024** [blackbeam/rust_mysql_common#137]
```json
{"finishTime": "2024-05-31 14:41:47", "signAmount": 105.0000000000, "payConfigId": 0, "couponAmount": 0, "promotionAmount": 0, "useRedEnvelopeAmount": 0}


```

ERROR  Jsonb convert error: Opaque, json: {ObjectKey(RawBytes { value: "finishTime", max_len: "65535" }): 2024-05-31 14:41:47, ObjectKey(RawBytes { value: "signAmount", max_len: "65535" }): <OpaqueValue { value_type: Const(MYSQL_TYPE_NEWDECIMAL, PhantomData<u8>), data: RawBytes { value: "\u{e}\n��\u{1d}�e\0\0", max_len: "4294967295" } }>, ObjectKey(RawBytes { value: "payConfigId", max_len: "65535" }): 0, ObjectKey(RawBytes { value: "couponAmount", max_len: "65535" }): 0, ObjectKey(RawBytes { value: "promotionAmount", max_len: "65535" }): 0, ObjectKey(RawBytes { value: "useRedEnvelopeAmount", max_len: "65535" }): 0},

Why can't the MYSQL_TYPE_NEWDECIMAL type be correctly mapped into JSON data?

**Comment by blackbeam** [comment]
@artorias1024, hi. There is nothing special in `MYSQL_TYPE_NEWDECIMAL` — the thing is that the `Opaque` practically means that the data is not JSON. How to convert a particular Opaque value to JSON is up to a user — I see no way for me, as a library developer, to choose which one is "the only correct".

If "signAmount" is a currency amount, then floats won't work and I suggest to use the JSON string (`"105.0000000000"`). Consider writing a wrapper that performs the desired conversion for your Opaque values.

**Comment by artorias1024** [comment]
> @artorias1024, hi. There is nothing special in `MYSQL_TYPE_NEWDECIMAL` — the thing is that the `Opaque` practically means that the data is not JSON. How to convert a particular Opaque value to JSON is up to a user — I see no way for me, as a library developer, to choose which one is "the only correct".
> 
> If "signAmount" is a currency amount, then floats won't work and I suggest to use the JSON string (`"105.0000000000"`). Consider writing a wrapper that performs the desired conversion for your Opaque values.
> 
> upd: use may want to use [this impl](https://docs.rs/mysql_common/latest/mysql_common/binlog/jsonb/enum.Value.html#impl-TryFrom%3CValue%3C'a%3E%3E-for-Value) as a reference

Thanks~
Thank you for your reply. I tried to manually retrieve the data from Opaque, but I found that it does not seem to be UTF-8 encoded, which has me confused. @blackbeam 
<img width="1776" alt="image" src="https://github.com/blackbeam/rust_mysql_common/assets/82564604/ba923a63-8a09-43bb-84a4-95e6bd776b01">

**Comment by blackbeam** [comment]
> Thank you for your reply. I tried to manually retrieve the data from Opaque, but I found that it does not seem to be UTF-8 encoded, which has me confused.

Hmm, consider trying https://docs.rs/mysql_common/latest/mysql_common/binlog/decimal/struct.Decimal.html#method.parse_bytes

**Comment by artorias1024** [comment]
> > Thank you for your reply. I tried to manually retrieve the data from Opaque, but I found that it does not seem to be UTF-8 encoded, which has me confused.
> 
> Hmm, consider trying https://docs.rs/mysql_common/latest/mysql_common/binlog/decimal/struct.Decimal.html#method.parse_bytes

<img width="963" alt="image" src="https://github.com/blackbeam/rust_mysql_common/assets/82564604/8b9e7633-b8ae-4955-8544-013d6e2ef74d">
<img width="932" alt="image" src="https://github.com/blackbeam/rust_mysql_common/assets/82564604/e9aa8e76-5992-4a64-9813-4e70d860f329">
<img width="898" alt="image" src="https://github.com/blackbeam/rust_mysql_common/assets/82564604/7305a9bd-32c0-4fa4-9539-3d8c648574c2">
I have already tried using this method to process it, but it seems to not work.

**Comment by blackbeam** [comment]
Oh, parse_bytes is bad naming. Try using [read_bin](https://docs.rs/mysql_common/latest/mysql_common/binlog/decimal/struct.Decimal.html#method.read_bin) instead the `precision` and `scale` seem to be in the first two bytes (see [here](https://github.com/mysql/mysql-server/blob/824e2b4064053f7daf17d7f3f84b7a3ed92e5fb4/sql-common/json_dom.cc#L1200-L1221))

**Comment by artorias1024** [comment]
> Oh, parse_bytes is bad naming. Try using [read_bin](https://docs.rs/mysql_common/latest/mysql_common/binlog/decimal/struct.Decimal.html#method.read_bin) instead — the `precision` and `scale` seem to be in the first two bytes (see [here](https://github.com/mysql/mysql-server/blob/824e2b4064053f7daf17d7f3f84b7a3ed92e5fb4/sql-common/json_dom.cc#L1200-L1221))

```rust
Value::Opaque(v) => {
            let data = v.data_raw();
            let decimal =  mysql_common::binlog::decimal::Decimal::read_bin(data, data[0] as usize, data[1] as usize, false ).unwrap();
            
            info!("Opaque: {:?},{:?}",decimal, decimal.to_string() );
            Ok(from_utf8(v.data_raw())?.into())
        }
```

<img width="1365" alt="image" src="https://github.com/blackbeam/rust_mysql_common/assets/82564604/f754e628-88f0-4e62-97a9-4174cd244cf3">
I tried it, but the result doesn't seem to be correct.

```json
{"finishTime": "2024-04-29 09:40:49", "signAmount": 26.0000000000, "couponAmount": 0, "promotionAmount": 0, "useRedEnvelopeAmount": 0}
```

**Comment by blackbeam** [comment]
Hmm. Seems like you need to take a `2..` slice of data in the first arg of read_bin

**Comment by artorias1024** [comment]
> Hmm. Seems like you need to take a `2..` slice of data in the first arg of read_bin

Ohh,  I made a stupid mistake. Thank you very much again.
