### ISSUE TITLE
Best way to handle financial/monetary calculation

### ISSUE THREAD

**Issue by surajpayu** [blackbeam/rust_mysql_common#14]
I am using my rust application to store financial data or amount in mysql db. I want my data to work correctly for a particular precision and scale. for e.g 12.345 (here scale is 3 and precision is 5). Since mysql::Value does not have support of BigDecimal, is it safe to use it for working with financial data. Can there be a loss of data while it is transferred from client to mysql and vice versa? What would be the best way to take care of this?

**Comment by blackbeam** [comment]
Fixed in [v16.1.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v16.1.0)
