### ISSUE TITLE
Implementation of binlog::misc::my_{datetime/time}_packed_from_binary functions do not match MySql implementation 

### ISSUE THREAD

**Issue by vassili-zarouba** [blackbeam/rust_mysql_common#145]
We are trying to read json opaque values for temporal types from the binlog, and discovered the binlog::misc::* functions which are meant to read the binary into i64, do not return correct result. After looking into the MySql source code for the same operation, it turned out the binlog::misc::* functions implementation is different from MySql, though the functions binlog::misc::{datetime_from_packed, time_from_packed} do match the MySql implementation. 
All worked, after we replaced the binlog::misc::{my_datetime_packed_from_binary, my_time_packed_from_binary} with a simple code which matches the MySql implementation.

Here is the MySql source code GitHub URL:
https://github.com/mysql/mysql-server/blob/mysql-8.0.39/sql-common/json_dom.cc#L721

**Comment by blackbeam** [comment]
Hi.

`my_datetime_packed_from_binary` and `my_time_packed_from_binary` are for reading on-disk binary representation (see [here](https://github.com/mysql/mysql-server/blob/mysql-8.0.39/mysys/my_time.cc#L1950) and [here](https://github.com/mysql/mysql-server/blob/mysql-8.0.39/mysys/my_time.cc#L1774)). They are used to read binlog values of types `MYSQL_TYPE_DATETIME2` and `MYSQL_TYPE_TIME2`.

**Comment by vassili-zarouba** [comment]
Thai you, @blackbeam

**Comment by blackbeam** [comment]
@vassili-zarouba, you may find #147 useful (see the docstring [here](https://github.com/blackbeam/rust_mysql_common/blob/master/src/binlog/jsonb.rs#L436-L451))
