### ISSUE TITLE
Could the `HlistFromRow` trait be publically referencable?

### ISSUE THREAD

**Issue by ch3pjw** [blackbeam/rust_mysql_common#149]
I'm wondering why the `HlistFromRow` trait is not publicly referencable (https://github.com/blackbeam/rust_mysql_common/blob/a8d4d642a612e6cb97faf710a5b1ce47fe0ec3ec/src/row/convert/frunk.rs#L68).

I'm trying to implement a trait with an associated `HList` type that I want to say is always `mysql_async::prelude::FromRow`, but I don't think I can say that without referencing `HlistFromRow` directly. I can work around that by putting a `FromRow` trait bound at the usage site, but that feels overly verbose given that the associated type in the trait I'm implementing should always be `FromRow`, and the constraint might propagate throughout the rest of my code where it doesn't need to be.

I've sketched the issue out in more detail here: https://gist.github.com/ch3pjw/5c9f5d320cf222eadc158829c4864279

Is your intent to make sure that no-one else can implement `HlistFromRow`? Is that necessary? Could that be achieved by using a sealed supertrait, if indeed it would be damaging if people were to try implementing it?

As a side point, should the trait be named with a capital `L` — `HListFromRow` — for consistency with `frunk`?

Thanks for the library, it's been extremely useful. I'm happy to submit a PR if you think that fits with your design goals.

**Comment by blackbeam** [comment]
@ch3pjw, hi.

Thanks for pointing this out. `HlistFromRow` turns out to be completely unnecessary and removed in #150. It is unfortunate that it pollutes the public interface.

Please wait for the next release.

**Comment by ch3pjw** [comment]
Great news, thanks!
