### ISSUE TITLE
Could not retrieve `alloc::string::String`: Couldn't convert the value `Null` to a desired type

### ISSUE THREAD

**Issue by Necoo33** [blackbeam/rust_mysql_common#151]
Hello, that package panics when i try to take a column which has a mysql "Null" type via `mysql_common::Row::take()` method. The error occures on this inner method:

mysql_common/src/value/convert/mod.rs:

```rust

    fn from_value(v: Value) -> Self {
        match Self::from_value_opt(v) {
            Ok(this) => this,
            Err(e) => panic!("Could not retrieve `{}`: {e}", type_name::<Self>(),),
        }
    }

```

So i think you should implement to returning "None" value from `mysql_common::Row::take()` method when a column has mysql's own `Null` value, that would be more idiomatic and better than panicking. I solved my problem via using `mysql_common::Row::take_opt()` though.

**Comment by blackbeam** [comment]
@Necoo33, hi.

Consider using the type that covers the value domain, for example if you schema allows NULL for a textual column holding UTF-8 then the proper type on the application side would be `Option<String>`

**Comment by Necoo33** [comment]
> @Necoo33, hi.
> 
> Consider using the type that covers the value domain, for example if you schema allows NULL for a textual column holding UTF-8 then the proper type on the application side would be `Option<String>`

i took that error on that code(that column has the mysql's own Null value):

```rust

let last_login: Option<String> = row.take("last_login");

```

Because of that, i have to convert previous code to that:

```rust

let last_login: Result<String, FromValueError> = row.take_opt("last_login").unwrap();
let last_login: Option<String> = match last_login {
            Ok(value) => Some(value),
            Err(_) => None
        };

```

And that worked well. But i think the `.take()` method shouldn't panic when it encounters mysql's null value.

**Comment by blackbeam** [comment]
Oh, I see.

`Row::take` might get confusing but it's logic mimics the [`Option::take`](https://doc.rust-lang.org/core/option/enum.Option.html#method.take) logic — it is intended to take out a value of type `T` but the value might be already taken so the method have to return `Option<T>` to be non-panicking. In other words if your proper column type is `Option<String>` then the expected output type of `Row::take` is `Option<Option<String>>`:

```rust
let last_login: Option<Option<String>> = row.take("last_login");
```

Also consider relying on the `FromRow` trait where possible — `Row::take` is a bit low-level.
