### ISSUE TITLE
Error for enum `#[derive(FromValue)]`

### ISSUE THREAD

**Issue by radiantBear** [blackbeam/rust_mysql_common#154]
Hello,

I'm trying to represent an enum from my database that is defined as:
```sql
`consume_meal` ENUM ('Breakfast', 'Lunch', 'Dinner', 'Snack') NOT NULL
```

In Rust, I am representing this as:
```rs
#[derive(FromValue)]
#[mysql(rename_all = "PascalCase")]
pub enum MealTime {
    Breakfast,
    Lunch,
    Dinner,
    Snack
}
```

Based on the [enum documentation](https://docs.rs/mysql_common/latest/mysql_common/#enums), it appears that this is all I need. However, I am getting a compile error:
```
error: FromValue: add #[mysql(explicit_invalid)] attribute to allow
  --> src/types.rs:47:5
   |
47 |     Breakfast,
   |     ^^^^^^^^^
```

If I update the struct to be:
```rs
#[derive(Debug, FromValue)]
#[mysql(rename_all = "PascalCase")]
pub enum MealTime {
    #[mysql(explicit_invalid)]
    Breakfast,
    Lunch,
    Dinner,
    Snack
}
```
I instead get the runtime error:
```
called `Result::unwrap()` on an `Err` value: MySqlError { ERROR 1265 (01000): Data truncated for column 'consume_meal' at row 1 }
```

What do I need to change in order to use `#[derive(FromValue)]`?

**Comment by blackbeam** [comment]
Hi. Please look into MySQL documentation on how enums work.

You need to define your first variant to equal 1, then there be no invalid values and explicit_invalid annotation will become unnecessary:


```rust
#[derive(FromValue)]
#[mysql(rename_all = "PascalCase")]
pub enum MealTime {
    Breakfast = 1,
    Lunch,
    Dinner,
    Snack,
}
```
