### ISSUE TITLE
Packets starting with 255 are not parsed

### ISSUE THREAD

**Issue by normano** [blackbeam/rust_mysql_common#22]
I was getting an error from MySQL via the binlog functionality after I enabled GTID and got the packet via the Error struct. Below is the description for parsing. I added for my own application and will probably port it to here.

https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html

MySQL Error Message struct description
Byte 1: 255, Error packet
Byte 2 - 3: Error Code
Byte 4 - 9 (depends on client protocol): Character "#" followed by Sql Error State
Byte 10 - infinity: Text

**Comment by blackbeam** [comment]
Oh. Thanks for report. Looks like I forgot to handle the [ErrPacket](https://github.com/blackbeam/rust_mysql_common/blob/master/src/packets.rs#L506) in `impl Stream for BinlogStream`.

**Comment by normano** [comment]
Ah ok, sorry about that.
