### ISSUE TITLE
Cannot use FromRow to Deserialize a Deserilized<T> object

### ISSUE THREAD

**Issue by lroux-at-jellysmack** [blackbeam/rust_mysql_common#27]
Hi,

I'm using the `mysql = "20.0.1"` crate in a project, which is based on your crate for `FromRow` & `FromValue` conversions, but there's a little problem with `Deserialized<T>`, it compiles, but *panics at runtime*, which is not only bad but also dangerous for subsequent crates that uses this project.

Here's the offending code:
```rust
// [...]

#[derive(Serialize, Deserialize, Debug)]
pub struct QueryableUser {
    pub id: u32,
    pub login: String
    pub email: String,
    pub display_name: String,
    pub status: String,
}

let username = "user1";
let user: Option<Deserialized<QueryableUser>> = "
    SELECT
       user_id as id,
        user_full_name as display_name,
        user_login as login,
        user_email as email,
        user_status as status
    FROM user
    WHERE user_login = :username"
    .with(params!(
        "username" => username)
    .first(&connection)?;
```
which compiles, but on calling the code:
```
thread '<unnamed>' panicked at 'Couldn't convert Row { id: Int(1), display_name: Bytes("John"), login: Bytes("user1"), email: Bytes("user1@..."), status: Bytes("VALIDATED") } to type mysql_common::value::json::Deserialized<QueryableUser>. (see FromRow documentation)', mysql_common-0.24.1/src/row/convert.rs:82:39
```

also it panics with `Option<serde_json::Value>` to instead of `Option<Deserialized<QueryableUser>>` which means it's probably not me having my struct broken in some way but rather the `FromRow` implementation for `Deserialized` is not made to handle this case properly in my understanding.

What could be done to be able to use the `FromRow` trait on `Deserialize` structs ?
Thanks a lot, if you have any question, or need help, don't hesitate :)

**Comment by blackbeam** [comment]
Hi. The `Deserialized` type is for [mysql JSON columns](https://dev.mysql.com/doc/refman/8.0/en/json.html#json-values).

I believe you are looking for `impl FromRow for QueryableUser`, but you have to define this impl yourself ATM. I have a macro for this somewhere in my recent projects. I'll try to find it.

**Comment by lroux-jellymack** [comment]
Hi,

Alright, but why the `Deserialized<T>` type implements `FromRow` then ?
it either:
- shouldn't compile if we try to do that
- should work to Deserialize a Row into a `T: DeserializeOwned`

**Comment by blackbeam** [comment]
> why the Deserialized<T> type implements FromRow then?

Because of `impl FromRow for T: FromValue`

> Deserialize a Row into a T: DeserializeOwned

Yeah. I want to add some kind of this in future.

**Comment by lroux-at-jellysmack** [comment]
> Yeah. I want to add some kind of this in future.
Cool, I bet it would be easy, I'll look onto it if I have some time if you want.

For now if you have the macro somewhere it would be very handy (for now I came up with a `.map` on the `Option<T>` and it works but it's not as elegant as a trait autoconversion :D)

Thanks :)

**Comment by blackbeam** [comment]
Sorry for delay.

Note, that **(i)** every field must implement `FromValue`, **(ii)** name of a struct field must be equal to the name of a column (you can tweak the macro to remove this limitation).

<details>
<summary>Here is the macro:</summary>

```rust
macro_rules! take {
    ($indexes:ident, $row:ident, $t:ty, $field:expr $(, $($restore:ident: $rt:ty),* )?) => {{
        let val = match $row.take_opt::<_, &str>($field) {
            Some(Ok(val)) => match <<$t as mysql_async::prelude::FromValue>::Intermediate as mysql_async::prelude::ConvIr<$t>>::new(val) {
                Ok(val) => Some(val),
                Err(mysql_async::FromValueError(val)) => {
                    $row.place(*$indexes.get($field).unwrap(), val.rollback());
                    None
                }
            },
            Some(_) => unreachable!(),
            None => None,
        };

        if let Some(val) = val {
            val
        } else {
            $(
                $(
                    $row.place(*$indexes.get(stringify!($restore)).unwrap(), ConvIr::<$rt>::rollback($restore));
                )*
            )?

            return Err(FromRowError($row));
        }
    }};
}

macro_rules! impl_from_row {
    (@take $i:ident, $r:ident, { $($prev_name:ident: $prev_type:ty,)* }, $cur_name:ident: $cur_type:ty, $next_name:ident: $next_type:ty, $($next:tt)* ) => {
        let $cur_name = take!($i, $r, $cur_type, stringify!($cur_name) $(, $prev_name: $prev_type )*);
        impl_from_row!(@take $i, $r, { $($prev_name: $prev_type,)* $cur_name: $cur_type, }, $next_name: $next_type, $($next)* )
    };
    (@take $i:ident, $r:ident, { $($prev_name:ident: $prev_type:ty,)* }, $cur_name:ident: $cur_type:ty, ) => {
        let $cur_name = take!($i, $r, $cur_type, stringify!($cur_name) $(, $prev_name: $prev_type )*);
    };
    ($t:ty { $($field_name:ident: $field_type:ty,)+ }) => {
        impl FromRow for $t {
            fn from_row_opt(
                mut row: mysql_async::Row,
            ) -> std::result::Result<Self, mysql_async::FromRowError>
            where
                Self: Sized,
            {
                let columns = row.columns();
                let indexes = columns.iter().enumerate().fold(
                    std::collections::HashMap::new(),
                    |mut acc, (i, col)| {
                        acc.insert(col.name_str(), i);
                        acc
                    },
                );

                impl_from_row!(@take indexes, row, { }, $($field_name: $field_type,)+ );

                Ok(Self {
                    $($field_name: $field_name.commit(),)+
                })
            }
        }
    };
}
```
</details>

And here is an example:

```rust
struct Foo {
    id: u64,
    name: String,
    created_at: NaiveDateTime,
}

impl_from_row!(Foo {
    id: u64,
    name: String,
    created_at: NaiveDateTime,
});
```

It isn't published because it's quite durty. I'll implement this as a derive macro.
