### ISSUE TITLE
Cryptic connection failure when server contains old password hashes

### ISSUE THREAD

**Issue by darrinsmart** [blackbeam/rust_mysql_common#35]
I was struggling to connect to database that was password-protected. get_conn() would always return the error:

`IoError { failed to fill whole buffer }`

Eventually I figured out it was because the particular user's account was still using the old pre-4.1, 16-byte password hash.

I was able to reset the password, upgrading it to the newer 4.1+ format, and then it would connect just fine. 

This is an acceptable workaround for me, and probably good advice for database admin anyway. But this crate would be a little more friendly if it could handle the old format password - like the mysql cli does - or otherwise generate an error that describes the old password format as being unsupported.

(I tested this with both mysql & mysql_async. I've figured this common crate is probably where the issue lies. Apologies if I've reported this in the wrong place)

Ref: https://dev.mysql.com/doc/refman/5.6/en/password-hashing.html

**Comment by blackbeam** [comment]
Hi.

Seems like a bug to me. I believe it should have said something like "unknown authentication plugin old_mysql_password".
I want to reproduce this. Which mysql version do you use?

**Comment by darrinsmart** [comment]
Thanks @blackbeam. The server I'm connecting to is MySQL 5.1 on CentOS 6 (yeah, I know...). mysql-5.1.73-8.el6_8.x86_64

I assumed this could be reproduced with a more current mysql by simply converting a password to the old hash:

`SET PASSWORD FOR 'some_user'@'some_host' = OLD_PASSWORD('password');`

but I guess it is quite possible that actually a compatibility issue with the old server version.

**Comment by blackbeam** [comment]
Fixed in v0.27.2
