### ISSUE TITLE
Stream read hangs on invalid SQL input

### ISSUE THREAD

**Issue by gliderkite** [blackbeam/rust_mysql_common#37]
Somewhat related to https://github.com/blackbeam/rust-mysql-simple/pull/285, when providing an invalid SQL as input to the `query_iter` method, the codec implementation hangs when reading from the stream. This is the line in question https://github.com/blackbeam/rust_mysql_common/blob/408effed435c059d80a9e708bcfa5d974527f476/src/proto/sync_framed.rs#L159

**Comment by blackbeam** [comment]
Hi. Could you please check whether `mysql` v21.0.1 fixes the issue?

**Comment by gliderkite** [comment]
Hey, thanks, I'll try it out over this weekend :)

**Comment by gliderkite** [comment]
Hi, v21.0.1 did fix the issue, thanks :) Now it doesn't hang anymore. However, `query_iter` returns an empty `QueryResult` (0 rows and 0 columns) when I use the invalid SQL as input, instead of returning an `Err`. Is this expected behavior?
