### ISSUE TITLE
SslRequest is not deserializing correctly

### ISSUE THREAD

**Issue by bsod90** [blackbeam/rust_mysql_common#48]
Hey, @blackbeam !
Sorry for the persistence, but I keep working on my MySQL proxy project and it seems like I found another little 🐞 
I was trying to `let r: SslRequest = buf.parse(()).unwrap()`, and it was failing with `Unknown flags in the raw value of CapabilityFlags (raw=11001111111111010111010000101)`.
I examined closer two versions of the handshake from the same MySQL client: the plain one and the one requesting SSL, and capability flags seemed to only differ in one bit:

<img width="384" alt="Screen Shot 2021-11-23 at 5 59 11 PM" src="https://user-images.githubusercontent.com/2292499/143157759-7b310684-3881-47db-a4bd-4340aa124415.png">

I didn't check, but I assume it's the `CLIENT_SSL` bit.

Later in my proxy code, I read the full `HandshakeResponse` using another struct from this library and it never fails on the regular handshake.

I assume the `SslRequest` parsing fails because there are some extra bits set by the newer MySQL-client which are yet unknown to the mysql_common library. After looking into the `HandshakeResponse` deserialization code, I came up with this small change that seems to be fixing the issue for me: https://github.com/bsod90/rust_mysql_common/commit/dcc68623da7432cce484851c387bb8c6d86549a5

I'm super new to Rust, as well as MySql protocol and I don't know the difference between `Cons` and `RawConst`, but intuitively it seems like one version allows (trims) unknown flags, and the other one doesn't. I'm not sure what should be the correct behavior here, but probably it should at least be consistent.. either both `HanshakeResponse` and `SslRequest` parsers should fail on unknown flags or silently allow them.

I'm personally looking for the latter behavior so, I'll go ahead with my fork for now :)

Thank you for the other handshake fix, btw ;)

**Comment by blackbeam** [comment]
Hi.

> I'm not sure what should be the correct behavior here, but probably it should at least be consistent.. either both HanshakeResponse and SslRequest parsers should fail on unknown flags or silently allow them.

Yeah, unknown capabilities must be allowed because it's the only way to properly negotiate them. Seems like I simply overlooked the `SslRequest`. This is fixed in [v0.28.0](https://github.com/blackbeam/rust_mysql_common/releases/tag/v0.28.0)

**Comment by blackbeam** [comment]
> Sorry for the persistence, but I keep working on my MySQL proxy project and it seems like I found another little 🐞

I'm interested in supporting this library, so please feel free to report any issues.
