### ISSUE TITLE
Bug in io::ReadMysqlExt::read_lenenc_int

### ISSUE THREAD

**Issue by aochagavia** [blackbeam/rust_mysql_common#49]
In this match statement:

https://github.com/blackbeam/rust_mysql_common/blob/ee906d91a254942a4d0006721bdd38511bfb175d/src/io.rs#L344-L353

The first match should be `x if x < 0xfb => ...` according to [the specification](https://dev.mysql.com/doc/internals/en/integer.html).

I expect the following test to fail currently because 250 does not round trip:

```rust
    #[test]
    fn lenenc_int_roundtrips() {
        let values = vec![
            0,
            250,
            251,
            5000,
            65_535,
            65_536,
            1_000_000,
            16_777_215,
            16_777_216,
            300_777_216,
        ];

        for value in values {
            let mut buf = Vec::new();
            buf.put_lenenc_int(value);

            let mut reader = std::io::Cursor::new(buf);
            let round_tripped = reader.read_lenenc_int().unwrap();
            assert_eq!(value, round_tripped);
        }
    }
```

I would have liked to open a PR for this, but for some reason the tests don't build on Windows (tried using the msvc and the gnu toolchains).

**Comment by blackbeam** [comment]
Published as [v0.28.2](https://github.com/blackbeam/rust_mysql_common/releases/tag/v0.28.2)
