### ISSUE TITLE
Crates.io link in README.md is wrong

### ISSUE THREAD

**Issue by lroux-at-jellysmack** [blackbeam/rust_mysql_common#53]
Hello,
I don't know if you noticed, but the badge link in your readme redirects to `https://crates.io/crates/cargo-readme` not to `https://crates.io/crates/mysql_common`, the displayed version on the badge seems good tho.

Have a nice day !

**Comment by lroux-at-jellysmack** [comment]
The offending line seems to be there: https://github.com/blackbeam/rust_mysql_common/blob/7f365a661dde8312cc2646cf4bae4e9144013bd1/README.tpl#L3

**Comment by blackbeam** [comment]
Oh! Thanks.
