### ISSUE TITLE
Invalid MySQL datetimes / dates cause a panic

### ISSUE THREAD

**Issue by kesmit13** [blackbeam/rust_mysql_common#62]
MySQL allows datetimes and dates to contain invalid values which get represented by `0000-00-00 00:00:00` and `0000-00-00` respectively. When these values are parsed and converted it results in a panic. There may not be an equivalent representation in Rust, but an alternative might be to surface it as a `NULL` value rather than panicking.

https://dev.mysql.com/doc/refman/8.0/en/datetime.html

**Comment by blackbeam** [comment]
Hi.

I don't think that it's a good idea for the driver to amend the server data in any way. I'd suggest to either:
* carefully choose the server mode (e.g. NO_ZERO_DATE)
* or to introduce a type, that fully covers the column domain

Please note, that `from_value::<T>` is meant to be used in cases, where conversion to `T` is infallible or panicking is OK. One should use [`from_value_opt`](https://docs.rs/mysql_async/latest/mysql_async/fn.from_value_opt.html#) ([`from_row_opt`](https://docs.rs/mysql_async/latest/mysql_async/fn.from_row_opt.html)) in other cases.
