### ISSUE TITLE
The example of the rust_mysql_common project.

### ISSUE THREAD

**Issue by dongzl** [blackbeam/rust_mysql_common#63]
Hello, I want to use this project `rust_mysql_common`, Does this project have example code, thanks.

**Comment by blackbeam** [comment]
Hi.

There are no examples, but you can look into the source of `mysql` and `mysql_async` crates.
Tests sources may also be helpful. Please note, that you need to be familiar with mysql internals.

**Comment by dongzl** [comment]
> 

OK, Thanks for reply.
