### ISSUE TITLE
Chrono types support cannot be enabled

### ISSUE THREAD

**Issue by Zomtir** [blackbeam/rust_mysql_common#66]
After upgrading some packages, I stumbled across this regression:
```
use chrono::{NaiveDate, NaiveDateTime};

let time_stamp : NaiveDateTime = NaiveDate::from_ymd(2016, 7, 8).and_hms(9, 10, 11);

let params = mysql::params! {
    "stamp" => &time_stamp,
};

> The trait `From<NaiveDateTime>` is not implemented for `mysql::Value`
```

My current Cargo.toml

```
[dependencies]
mysql = "22.1.0"
mysql_common = { version = "0.29.0", features = ["time03", "chrono", "frunk"]}
chrono = { version = "0.4", features = ["serde"] }
```
I could narrow this down to a change between 0.27.5 and 0.28.0, this is also reflected by the docs. Notice that NativeDateTime and related chrono implementations went missing.

https://docs.rs/mysql_common/0.27.5/mysql_common/value/convert/trait.FromValue.html
https://docs.rs/mysql_common/0.28.0/mysql_common/value/convert/trait.FromValue.html

```
git rev-list --ancestry-path v0.27.5..v0.28.0
[...]
0d2fbd6b4ad2331c6f2ff5ad2dbb4cf4cfe48059
[...]
```

I assume this happened due to 0d2fbd6b4ad2331c6f2ff5ad2dbb4cf4cfe48059, which removed chrono as default feature. This resulted in the documentation no longer reflecting optional features. The core rust repo has a discussion about how to (or rather not to) document optional features (https://github.com/rust-lang/rust/issues/43781).

After all, FromValue is not available despite enabling the "chrono" feature in the mysql_common dependency. I might have made a mistake in using the new optional features.

**Comment by Zomtir** [comment]
I figured I can use mysql_common::params for converting the value, but the mysql::PooledConn only takes mysql::params. And conversion from mysql_common::params to mysql::params is not implemented:

```
use chrono::{NaiveDate, NaiveDateTime};

let time_stamp : NaiveDateTime = NaiveDate::from_ymd(2016, 7, 8).and_hms(9, 10, 11);

let params = mysql_common::params! {
    "stamp" => &time_stamp,
};

let stmt = conn.prep("SOME SQL STATEMENT USING :stamp").unwrap();

let conn : mysql::PooledConn;
conn.exec_first::<u32,_,_>(&stmt, &params);

> the trait `From<mysql_common::params::Params>` is not implemented for `mysql::Params`
```

I guess the easiest way to solve that would be to change the defaults in the mysql crate (Cargo.toml snippet):

```
[features]
default = [
    # set of enabled-by-default mysql_common features
    "mysql_common/chrono",
]
```

**Comment by blackbeam** [comment]
Hi.
mysql v22.1.0 uses mysql_common v0.28 (not v0.29). Please change your cargo.toml accordingly.

**Comment by Zomtir** [comment]
That fixed it...
