### ISSUE TITLE
From_row for more than 12 parameters

### ISSUE THREAD

**Issue by Geigerkind** [blackbeam/rust_mysql_common#9]
Hey!
Im new to rust and I recently began a project using your mysql crate. Now, I ran into a problem where I wanted to fetch more than 12 columns with from_row. Is there Any way to implement it myself? Or any workaround where I can just get everything and then sort it out myself?

I guess I could query the same table two times, but thats not really clean.

Cheers!

**Comment by blackbeam** [comment]
Hi.

For rows of arity > 12 you can use `Row::take` to extract individual columns.

Please look into the (`Row` docs)[https://docs.rs/mysql/15.1.0/mysql/struct.Row.html]
Also look into the (`Stmt::execute` docs)[https://docs.rs/mysql/15.1.0/mysql/struct.Stmt.html#method.execute]
